// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package main

// ConversationSubmitRequest defines model for ConversationSubmitRequest.
type ConversationSubmitRequest struct {
	ConversationId *string `json:"conversationId,omitempty"`
	Model          string  `json:"model"`
	Prompt         string  `json:"prompt"`
}

// ConversationSubmitResponse defines model for ConversationSubmitResponse.
type ConversationSubmitResponse struct {
	ConversationId string `json:"conversationId"`
	Message        string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// SubmitConversationJSONRequestBody defines body for SubmitConversation for application/json ContentType.
type SubmitConversationJSONRequestBody = ConversationSubmitRequest
